### ISSUE TITLE
Some notes after working with this boilerplate

### ISSUE THREAD

**Issue by patryk-smc** [danurbanowicz/jekyll-netlify-boilerplate#5]
Hey Dan,
thank you for doing this. That's the first time I'm playing with Jekyll and Netlify and it's indeed interesting. That boilerplate really helped me to understand the whole thing. The way how you do SCSS is also interesting, I never saw something similar before.

I took some notes whenever I met any obstacles while working with it today

- Contact form styling differs mobile vs desktop
- No blockquote CSS
- Numbered and unorganized lists do not have proper styling
- Mobile menu is not scrollable on the longer menus - words break into two lines instead

(personal preferences)
- No margins in the header
- Images in pages/posts could be wider then text ([like here](http://pixyll.com/jekyll/pixyll/2014/06/10/see-pixyll-in-action/))

Hope that this may help you develop this in future,
If I notice anything else I can add it here.
Cheers

**Comment by danurbanowicz** [comment]
Feel free to submit a PR with any changes - I'm sure that there are loads of things that could be improved and I would love to see more contributions to the project!

**Comment by SherG** [comment]
Hi Dan: Thanks for the beautiful, clean boilerplate. Question: I can't seem to get <ul>s or <ol>s to display. I've tried putting the HTML for them into Markup but that didn't work. Wondering if you have any tips on this. Thanks!

**Comment by danurbanowicz** [comment]
Hi! The default user agent styling for lists is disabled in this file: _sass/partials/_utilities.scss

If you want you can remove the following CSS which will bring back the default user agent styling, or you can add your own.

```
ul,
ol,
dl {
	list-style: none;
}
```

Either way, it's totally up to you how you do it. Good luck!

**Comment by SherG** [comment]
Thanks very much, Dan!

**Comment by danurbanowicz** [comment]
Closing this for now, but let me know if you feel this still needs looking at and I will re-open. Thanks.
