### ISSUE TITLE
CMS Post Publish Date widget can write invalid numbers of seconds, causing Jekyll build failure

### ISSUE THREAD

**Issue by karlshaver** [danurbanowicz/jekyll-netlify-boilerplate#7]
In `admin/config.yml`, the Posts collection date field is configured as following:
`- {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:MM:SS"}`
Netlify CMS's datetime widget uses [Moment.js formatting](https://momentjs.com/docs/#/parsing/string-format/). Capital S in "HH:MM:SS" indicates "fractional seconds", allowing the widget to sometimes write times such as "03:06:84". The invalid number of seconds (84) causes Jekyll build failure.
Solution: `format: YYYY-MM-DD HH:mm:ss` indicating 24hr hours, minutes (as opposed to months), and normal seconds (as opposed to fractional)

Screenshot:
<img width="516" alt="Screen Shot 2019-06-11 at 3 03 17 PM" src="https://user-images.githubusercontent.com/17164008/59300602-97509a80-8c5d-11e9-83c5-060580dfdf66.png">

**Comment by danurbanowicz** [comment]
Fixed by #8 thanks @karlshaver !
