### ISSUE TITLE
CMS Not working properly on mobile

### ISSUE THREAD

**Issue by alediez2048** [danurbanowicz/jekyll-netlify-boilerplate#9]
Hi everybody, I'm currently having some issues with the boilerplate on mobile. I can authenticate my credentials through my phone, but once I get access to the Netlify CMS it seems to be broken and you can't really edit the content. Has anybody else ran into this issue? Is there any way to fix the UI so you can edit content on mobile?

**Comment by danurbanowicz** [comment]
This issue is out of scope for this project and should instead be opened on the [Netlify CMS](https://github.com/netlify/netlify-cms) repo. Closing this now.
